# -*- coding: utf-8 -*-
"""week_2_class_3_string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SxntcfJy-HnNaAXy_Gp8hoOU555hhPst
"""

data = 'pakistan zindabad' 213#$@9djsad "hello world'

print (type(data))

data = 'pakistan zindabad\' 213#$@9djsad "hello world'

print(data)
print (type(data))

fgd = "line of control 1"\
"line of control 2"\
"line of control 3"

print(fgd)
print(type(fgd))

fgd = """
hello world
pakistan zindabad
karachi the city of lights
"""
fgd

fgd = """
hello world
pakistan zindabad
karachi the city of lights
"""

print(fgd)
print(type(fgd))

#concatination

"1" + 1

"1" + "1"

1+1

a = input("enter no1")
b = input("enter no2")

print(type(a), type(b))
print(a + b)

#type casting

a = "7"
print(a, type(a))
a = int(a)
print(a, type(a))

a = "7"
print(a, type(a))
a = float(a)
print(a, type(a))

a = input("enter no1")
b = input("enter no2")

print(type(a), type(b))
print(a + b)

#card making
roll_no = 2000
name = "feroz gul"
fname = "khameeso khan"
contact_no = "03053075434"
card = "NED university \nstudent roll no:" + str(roll_no)+\
"\nstudent name: " + name + "\nfather's name:" +fname\
+"\ncontact no:" +contact_no


print(card)

